version: '3.8'

services:
  # Discovery Server (Eureka)
  discovery:
    build:
      context: ./discovery
      dockerfile: Dockerfile
    container_name: discovery
    hostname: discovery
    ports:
      - "8761:8761"
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
    restart: unless-stopped

  # Auth Service
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    hostname: auth-service
    ports:
      - "8088:8088"
    depends_on:
      - discovery
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery:8761/eureka
      - SPRING_APPLICATION_NAME=auth-service
      - SPRING_SECURITY_USER_NAME=admin
      - SPRING_SECURITY_USER_PASSWORD=admin
    restart: unless-stopped

  # API Gateway
  gateway:
    build:
      context: ./gatway
      dockerfile: Dockerfile
    container_name: gateway
    hostname: gateway
    ports:
      - "8222:8222"
    depends_on:
      - discovery
      - auth-service
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery:8761/eureka
      - SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_ENABLED=true
      - SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_LOWER_CASE_SERVICE_ID=true
    restart: unless-stopped

  # Articles Service
  articles-service:
    build:
      context: ./articles-services
      dockerfile: Dockerfile
    container_name: articles-service
    hostname: articles-service
    ports:
      - "8084:8084"
    depends_on:
      - discovery
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery:8761/eureka
      - SPRING_APPLICATION_NAME=articles-service
    restart: unless-stopped

  # Mapping Service
  mapping-service:
    build:
      context: ./mapping-service
      dockerfile: Dockerfile
    container_name: mapping-service
    hostname: mapping-service
    ports:
      - "8087:8087"
    depends_on:
      - discovery
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery:8761/eureka
      - SPRING_APPLICATION_NAME=mapping-service
    restart: unless-stopped

  # Media Service
  media-service:
    build:
      context: ./media
      dockerfile: Dockerfile
    container_name: media-service
    hostname: media-service
    ports:
      - "8086:8086"
    depends_on:
      - discovery
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery:8761/eureka
      - SPRING_APPLICATION_NAME=media-service
    restart: unless-stopped

  # Site Patrimonial Service
  site-service:
    build:
      context: ./site-patrimonial
      dockerfile: Dockerfile
    container_name: site-service
    hostname: site-service
    ports:
      - "8085:8085"
    depends_on:
      - discovery
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery:8761/eureka
      - SPRING_APPLICATION_NAME=site-service
    restart: unless-stopped

  # Frontend Application
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: frontend
    hostname: frontend
    ports:
      - "80:80"
    networks:
      - app-network
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
      - API_BASE_URL=http://16.171.111.247:8222
    depends_on:
      - gateway
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
