version: '3.8'

services:
  # Discovery Server (Eureka)
  discovery:
    build:
      context: ./discovery
      dockerfile: Dockerfile
    container_name: discovery
    hostname: discovery
    ports:
      - "8761:8761"
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
    restart: unless-stopped

  # API Gateway
  gatway:
    build:
      context: ./gatway
      dockerfile: Dockerfile
    container_name: gatway
    hostname: gatway
    ports:
      - "8222:8222"
    depends_on:
      - discovery
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery:8761/eureka
      - SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_ENABLED=true
      - SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_LOWER_CASE_SERVICE_ID=true
    restart: unless-stopped

  # Articles Service
  articles-services:
    build:
      context: ./articles-services
      dockerfile: Dockerfile
    container_name: articles-services
    hostname: articles-services
    ports:
      - "8084:8084"
    depends_on:
      - discovery
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery:8761/eureka
      - SPRING_APPLICATION_NAME=articles-services
    restart: unless-stopped

  # Mapping Service
  mapping-service:
    build:
      context: ./mapping-service
      dockerfile: Dockerfile
    container_name: mapping-service
    hostname: mapping-service
    ports:
      - "8087:8087"
    depends_on:
      - discovery
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery:8761/eureka
      - SPRING_APPLICATION_NAME=mapping-service
    restart: unless-stopped

  # Media Service
  media:
    build:
      context: ./media
      dockerfile: Dockerfile
    container_name: media
    hostname: media
    ports:
      - "8086:8086"
    depends_on:
      - discovery
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery:8761/eureka
      - SPRING_APPLICATION_NAME=media
    restart: unless-stopped

  # Site Patrimonial Service
  site-patrimonial:
    build:
      context: ./site-patrimonial
      dockerfile: Dockerfile
    container_name: site-patrimonial
    hostname: site-patrimonial
    ports:
      - "8085:8085"
    depends_on:
      - discovery
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery:8761/eureka
      - SPRING_APPLICATION_NAME=site-patrimonial
    restart: unless-stopped

  # Frontend Application
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: frontend
    hostname: frontend
    ports:
      - "80:80"
    networks:
      - app-network
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
      - API_BASE_URL=http://51.20.60.69:8222
    depends_on:
      - gatway
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
