apiVersion: v1
kind: Service
metadata:
  name: articles-k8s-service
spec:
  selector:
    app: articles-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
