apiVersion: apps/v1
kind: Deployment
metadata:
  name: patrimonial-deployment

spec:
  replicas: 3
  selector:
    matchLabels:
      app: patrimonial-deployment
  template:
    metadata:
      labels:
        app: patrimonial-deployment
    spec:
      containers:
        - name: site-patrimonial-service
          image: site-patrimonial-service
          ports:
            - containerPort: 80
