apiVersion: v1
kind: Service
metadata:
  name: site-service
  labels:
    app: site
spec:
  ports:
  - port: 8085
    targetPort: 8085
  selector:
    app: site
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: site-deployment
  labels:
    app: site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: site
  template:
    metadata:
      labels:
        app: site
    spec:
      containers:
      - name: site
        image: kamelaloui/pfee_app-site-service:latest
        ports:
        - containerPort: 8085
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: "http://discovery-service:8761/eureka"
