pipeline {
    agent any

    environment {
        // Définir des variables d'environnement ici, si nécessaire
    }

    stages {
        stage('Checkout') {
            steps {
                // Vérifiez votre code source depuis un dépôt Git
                git url: 'https://github.com/KAMELALOUI/patrimoine-kamel.git', branch: 'main'
            }
        }
        
        stage('Build') {
            steps {
                script {
                    // Utilisez un bloc de script pour exécuter des commandes personnalisées
                    if (fileExists('pom.xml')) {
                        // Si le projet utilise Maven
                        sh 'mvn clean install'
                    } else if (fileExists('build.gradle')) {
                        // Si le projet utilise Gradle
                        sh './gradlew build'
                    } else if (fileExists('package.json')) {
                        // Si le projet utilise Node.js/NPM
                        sh 'npm install'
                        sh 'npm run build'
                    } else {
                        error 'Aucun fichier de build détecté (pom.xml, build.gradle, package.json).'
                    }
                }
            }
        }
        
        stage('Test') {
            steps {
                script {
                    // Exécutez des tests basés sur le type de projet
                    if (fileExists('pom.xml')) {
                        sh 'mvn test'
                    } else if (fileExists('build.gradle')) {
                        sh './gradlew test'
                    } else if (fileExists('package.json')) {
                        sh 'npm test'
                    } else {
                        echo 'Aucun fichier de test détecté (pom.xml, build.gradle, package.json).'
                    }
                }
            }
        }
        
        stage('Deploy') {
            steps {
                script {
                    // Ajoutez vos étapes de déploiement ici
                    // Par exemple, déploiement sur un serveur ou un cloud
                    echo 'Déploiement...'
                }
            }
        }
    }

    post {
        always {
            // Actions à effectuer à la fin, que le build réussisse ou échoue
            echo 'Pipeline terminé.'
        }
        success {
            // Actions à effectuer si le build réussit
            echo 'Build réussi.'
        }
        failure {
            // Actions à effectuer si le build échoue
            echo 'Build échoué.'
        }
    }
}
