pipeline {
    agent any

    environment {
        NODE_HOME = tool name: 'NodeJS'
        PATH = "${env.NODE_HOME}/bin:${env.PATH}"
    }

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/KAMELALOUI/patrimoine-kamel.git', branch: 'main', credentialsId: 'your-github-credentials'
            }
        }
        
        stage('Build') {
            steps {
                dir('front') {
                    sh 'npm install'
                    sh 'npm run build -- --prod'
                }
            }
        }
        
        stage('Test') {
            steps {
                dir('front') {
                    sh 'npm test'
                }
            }
        }
        
        stage('Archive Artifacts') {
            steps {
                archiveArtifacts artifacts: 'front/dist/*', fingerprint: true
            }
        }
    }
    
    post {
        always {
            junit 'front/test-results.xml'
        }
        failure {
            mail to: 'your-email@example.com',
                 subject: "Failed Pipeline: ${currentBuild.fullDisplayName}",
                 body: "Something is wrong with ${env.BUILD_URL}"
        }
    }
}
