pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/KAMELALOUI/patrimoine-kamel.git'
            }
        }
        
        stage('Build') {
            steps {
                echo 'Building...'
                // sh 'mvn clean install' // Exemple pour un projet Maven
                // sh 'npm install' // Exemple pour un projet Node.js
            }
        }
        
        stage('Test') {
            steps {
                echo 'Testing...'
                // sh 'mvn test' // Exemple pour un projet Maven
                // sh 'npm test' // Exemple pour un projet Node.js
            }
        }
        
        stage('Deploy') {
            steps {
                echo 'Deploying...'
                // Commandes de déploiement
            }
        }
    }
    
    post {
        always {
            echo 'Pipeline terminé.'
        }
        success {
            echo 'Pipeline réussi.'
        }
        failure {
            echo 'Pipeline échoué.'
        }
    }
}
