apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-deployment

spec:
  replicas: 3
  selector:
    matchLabels:
      app: discovery-deployment
  template:
    metadata:
      labels:
        app: discovery-deployment
    spec:
      containers:
        - name: media-service
          image: discovery-service
          ports:
            - containerPort: 80
