apiVersion: v1
kind: Service
metadata:
  name: discovery-k8s-service
spec:
  selector:
    app: discovery-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
